### ISSUE TITLE
Lag on Factions

### ISSUE THREAD

**Issue by Paige-leee** [RoyalRaid/VenomPvP#10]
The terrible lag is back.  Don't know if it's server lag or ddos

**Comment by Paige-leee** [comment]
-might be pumpkin farm on a timer

**Comment by Zaid-Ali** [comment]
Checked all online players: There were no laggy farms active (i.e. Bud Farms). I'm guessing this is another memory usage issue.

**Comment by RoyalRaid** [comment]
Was still recovering from a attack and didnt restart properly. 
Tweaked some firewall settings and havent been attacked since. Gonna set to resolved
