### ISSUE TITLE
/list is broken on Factions?

### ISSUE THREAD

**Issue by Paige-leee** [RoyalRaid/VenomPvP#19]
https://gyazo.com/89f0829ae88a7fcf319e7ef758f6c4b6

I was the only one on

**Comment by RoyalRaid** [comment]
Forwarded this bug to dev. Will get back to this issue once he has fixed it!

Thanks

**Comment by Zaid-Ali** [comment]
https://www.spigotmc.org/resources/pstafflist-a-staff-list-in-a-gui.24838/

This plugin allows for you to hook it into bungee cord; when a player does /staff it will tell the player the staff members online and on which server: http://prntscr.com/dusg2u

**Comment by RoyalRaid** [comment]
https://puu.sh/tlv8q/477e033884.png
Umm i would buy it but......

**Comment by Zaid-Ali** [comment]
The plugin developer had a mental breakdown, he will lower the price to around ~$10 soon.

**Comment by RoyalRaid** [comment]
Alright ill keep my eye on it, not sure why he would do that for xD

**Comment by RoyalRaid** [comment]
Implemented a staff GUI, command /staff
Will be implemented after auto restart in a hour

**Comment by Zaid-Ali** [comment]
<3
