### ISSUE TITLE
Staff Reform ideas. @Matt read this

### ISSUE THREAD

**Issue by Blackouma** [RoyalRaid/VenomPvP#20]
**Commandlogger.**
To better watch for staff abuse. This would probably need to be a custom plugin. We need to be able to pick what accounts and commands it should commandlog. Me and Jackson would either need console access or a command in-game which gives you a link to view the commandlogs.

**Limited /staff**
To allow even the lowest of ranks to watch for hackers. This would be like your normal /staff, but it would have to be limited. Meaning that we can set the area where it can be used. So that staff only can use it in fps, event arenas, duel arenas, the warzone and more. 

Matt, I'd like you to talk to your plugin people and see if this is possible.

**This is an ongoing issue, please do not close or resolve this. It may or may not be edited in the future.**

**Comment by RoyalRaid** [comment]
Yeah im aware this has been quite a large issue. The dev has been flat out recently as we are not the only server he works for. Wait times have picked up a bit over the christmas break time. I'm still in discussion with him about a /staff plugin that will be much more stable and have the features we want

As for command logger, we have a plugin that does this but to access it you would need server FTP access which i dont feel 100% comfortable just yet. Unless ofc i could get something coded that could display like a easy to read list ingame
