### ISSUE TITLE
Forums SnrMod & Admin Rank Missing Permissions

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#22]
Currently as Senior Mod on the forums I do not have permission to create conversations with other players - This is helpful when they require assistance and prevents me spamming threads to help them.

Senior Mod rank is also missing the ability to change their own signatures. http://prntscr.com/dr2xpm My own signature is very large and I cannot remove it.
 
We are also not able to change our usernames which would allow for us to change inappropriate usernames.

Make these changes for the **Senior-Mod and Admin Rank**.

**Comment by RoyalRaid** [comment]
All fixed, You should be able to edit your signature as well as create conversations
