### ISSUE TITLE
Grace Period on initial log in to Venom

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#25]
We have explorers joining for the first time, ready to go and build a base and then getting killed by other players in diamond armor, they stand no chance, and leave. 

Might as well add a "Grace Period" (period of time in which the player cannot get hit and cannot hit players) so that the explorers are more likely to go out, build a base and actually have a chance to enjoy Venom - could have a positive impact on the number of explorers that actually **stay** on Venom.

The Grace Period should be somewhere around 30 minutes.

**Comment by RoyalRaid** [comment]
So like a PvP Timer?

**Comment by Zaid-Ali** [comment]
Try it. Will be useful alongside the AD in feb with mostly new players joining.
