### ISSUE TITLE
FIX FOUND > [TYPES OF DOORS] Need adding to claimed territory

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#32]
I tested a couple of doors to check if they could not be opened by enemy factions and I found a couple of door types that need to be added to the list of inaccessible (can't use) items in the config as I was able to open them in enemy territory:

VIDEO: https://youtu.be/vgl5oMaOUm8

List of Door Types that need adding: 
- Birch
- Acacia
- Spruce
- Jungle
- Dark Oak

**Comment by Zaid-Ali** [comment]
Fix found (the dev is in-active af):

WATCH THE VIDEO: 

[https://youtu.be/vgl5oMaOUm8](url)



Paste these into

"territoryProtectedMaterials": AND "territoryProtectedMaterialsWhenOffline": [

"WOODEN_DOOR",
"SPRUCE_DOOR",
"BIRCH_DOOR",
"ACACIA_DOOR",
"JUNGLE_DOOR",
"DARK_OAK_DOOR",

**Comment by RoyalRaid** [comment]
Ah you're a legend <3
I've added them to the config, Double check for me :)

**Comment by Zaid-Ali** [comment]
Changes to config have taken effect. Works fine.
