### ISSUE TITLE
FIX FOUND > [/f top] Add Zombie Pigman and Cave Spider Spawners

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#36]
Add Zombie Pigman and Cave Spider Spawners to f top. 

Zombie Pigman - $800,000
Cave Spider - $You Choose

**Comment by RoyalRaid** [comment]
Ah what a fucking retard xD
Nice find btw, i've removed the '_' from the mob names
~ Will be applied after server restart
