### ISSUE TITLE
Crate reform

### ISSUE THREAD

**Issue by Kauldwin** [RoyalRaid/VenomPvP#38]
Adding more rewards that are WORTH it for crates, Add the possibility to win a python rank to twitter and voteparty and cobra to venom

and then the rank I want to work on, either Mamba or Basilisk  - PM FOR INFO  

*Matt please send me a copy of the deluxechat plugin, I want to setup this "vote crate rank" to encourage voting (Refereed above)

**Comment by Blackouma** [comment]
Cobra? Ain't that a bit much. What would the percentage be?

**Comment by OkHeigo** [comment]
It's Venom crate, the % doesn't have to be THAT low

**Comment by RoyalRaid** [comment]
Adding ranks to crates is a bit stupid imo. If they are anaconda and win python its just gonna cause issues with them losing their rank, making them more worthless.
