### ISSUE TITLE
[/votetop] 

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#47]
http://prntscr.com/dti31e

IGN: 1andonlyjoker has double the amount of possible votes........??

**Comment by RoyalRaid** [comment]
weird, everyone kinda caught up: https://puu.sh/tkwIB/117545b8e0.png
Are you aware of how he might of done it?

**Comment by Zaid-Ali** [comment]
Apparently he didn't log into the server for a while before reset, yet he kept voting. Once he joined (this reset) all the votes went through and took effect.

**Comment by RoyalRaid** [comment]
ah okay, Closing the issue then
