### ISSUE TITLE
New Plugin: CPS Checker (BAEEEEEEEEEE)

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#49]
https://www.spigotmc.org/resources/ezdetect-amazing-cps-detection-configurable-lightweight.28005/

or 

https://www.spigotmc.org/resources/cps-alert-original.19181/

Checks CPS of each player, notifies staff if above a set CPS.

Make the MAX CPS 10 ish so we get notified if its any higher.

**Comment by RoyalRaid** [comment]
Great plugin find, Will purchase the $3.50 one as it looks a lot more reliable. Will install right now :)
Which staff did you want me to give the notification perms too?

**Comment by RoyalRaid** [comment]
Plugin is installed, gave the permission to all staff members as its kinda necessary

**Comment by Zaid-Ali** [comment]
"Which staff did you want me to give the notification perms too?"

Moderator and UP.
