### ISSUE TITLE
Maximum tags reached

### ISSUE THREAD

**Issue by Kauldwin** [RoyalRaid/VenomPvP#5]
Created tags having a maximum amount on the server, Player fixi101 bought a custom tag yesterday I saw it on /tags as of today its been removed not by me or another staff member, I noticed Tags being overwritten yesterday, with two custom tags i was making, and a tag for the Holidays.

**Created "HolidayChaos" tag, removed a already made tag**

**Comment by RoyalRaid** [comment]
This is because when you create a tag via ingame command it interfears with the way store is setup for custom tags. Please refrain yourself from creating custom tags via the ingame commands
