### ISSUE TITLE
[BUMP] Disable slime blocks

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#51]
I'm pretty sure there is such a thing as Phase Cannons (they bypass walls etc.) which work by using slime blocks. They are super op and need disabling.

**Comment by RoyalRaid** [comment]
when you say disabling slime blocks you mean like placing them etc.

**Comment by Zaid-Ali** [comment]
Correct, you should not be able to place them

**Comment by Zaid-Ali** [comment]
Blacklist in essentials.

**Comment by Zaid-Ali** [comment]
^
