### ISSUE TITLE
[/wild] Failed to find a safe location after 100 attempts.

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#52]
./wild has been failing for most players when the attempt the command; tested myself and it came up with the stated messages:

"Searching for a random location in Wilderness ..."
"Failed to find a safe location after 100 attempts."

Possibly try removing: http://prntscr.com/dus8lx (They are not needed)

**Comment by RoyalRaid** [comment]
not this again, This happened a few months ago and i removed everything except lava and cactus. Most i can do is increase radius a bit more or find another plugin for wild since fbasics doesnt seem to be doing it properly

**Comment by Zaid-Ali** [comment]
If this error keeps occuring you are better off disabling it in the FBasics config and using one of these:

**(Tested on server - No errors):**

https://www.spigotmc.org/resources/wildtp.11653/
This one is a simple /wild; /wilderness command - No major performance impact detected while using.

https://www.spigotmc.org/resources/wilderness-tp.18431/
This one has a bunch of other things such as sign and portal compatibility. - No major issues, no major performance impact.

**Comment by RoyalRaid** [comment]
List of what i've done

- Disabled Fbasics's version of /wild
- Pre-configured the new "WildTP" plugin to these settings: http://pastebin.com/tWwJGhp5
- Imported the new config and jar file to the factions server. 
- Added permissions to the default group.

All these changes will take effect once the auto restart initializes tonight.
