### ISSUE TITLE
[Anti PotLag] Plugin (BAEEEEEEEE)

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#53]
Self explanatory... Need a plugin that increases the speed at which instant health 2 effects the player after being thrown.

Only public plugin out there is https://www.spigotmc.org/resources/fastpot-anti-pot-lag.29592/

I tested it and if you use it you must change the config value "speed" to 3.0 as 4.0 is too fast and will cause errors. 100% works with no direct impact on performance.

THIS WOULD BE GREAT

**Comment by RoyalRaid** [comment]
Believe it or not, We're already using it. We've been using it since the start of the reset. Although its only recently he added a config so i might update it and set to 3.0.
Changes will make effect after a restart

**Comment by RoyalRaid** [comment]
Plugin is in, did some brief testing before and after, did notice a smaller improvement, nothing major though
