### ISSUE TITLE
[Deluxe Chat Config] Testing

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#54]
Give the Deluxe Chat Config to @Kauldwin so he can refine https://github.com/RoyalRaid/VenomPvP/issues/6. 

Logic is sound; with separate ranks given separate roles on Venom depending on what the player is capable of. All you have to do is be willing to distribute power to whom you trust; it's what will hold Venom back in the future.

**Comment by Zaid-Ali** [comment]
#6

**Comment by RoyalRaid** [comment]
Here is our Deluxe Chat format: http://pastebin.com/ZiHPU63S

**Comment by Zaid-Ali** [comment]
Note: could you also send groups.yml from Group Manager so he can setup the ranks/inheritance.

**Comment by RoyalRaid** [comment]
Groups.yml: http://pastebin.com/az1f2CdE
