### ISSUE TITLE
[Forums] Fix the Thread Title Capital Letters Issue

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#55]
I'm pretty sure you are aware (for example) when you attempt to title a thread:

"Official Rules and Regulations" changes to "Official **r**ules and **r**egulations". LINK: http://prntscr.com/dv5gon

All letters apart from the first are reverted to their lowercase format. _I WILL LOVE YOU IF YOU FIX THIS_ **<3**. (OCD) I'm pretty sure its either an Xenforo Add-on or Setting.

**Comment by RoyalRaid** [comment]
I can fix it but it will then allow people to make thread titles with all CAPS, let me know if you wanna go ahead

**Comment by Zaid-Ali** [comment]
I check the forums everyday. If there are any problems with players making thread titles with all CAPS I will deal with it.

So go ahead.  <3

**Comment by RoyalRaid** [comment]
Go ahead and try it now,
See if it works, if so mark as resolved :)

**Comment by Zaid-Ali** [comment]
<3
Works fine. Changed all the official threads (formats) titles to make it more aesthetically pleasing.
