### ISSUE TITLE
[Forums] <3 Making it better

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#57]
> @Blackouma @Kauldwin @csPsycho @RoyalRaid @Paige-leee 
> 
> The layout of our Forums needs improving to make more sense as well as small aesthetic improvements ....
> Open these side by side, have a read through the annotations:
> 
> http://prntscr.com/dv68bb
> http://prntscr.com/dv676q
> 
> ### Changes suggested to be made (in order as shown in screenshots):
> 
> **"Announcements, Applications & Help"**
> - Rename to "Server Information" (that's what it is)
> - RENAME "Trial Mod Applications" to "Staff Applications"
> - Change "Youtuber Applications" to "Social Applications" (which accounts for Twitch applications as well)
> - Move "Information, Guides & Rules" up, to below "Announcements" (easier to access)
> - Rename "Donation Enquiries" to "Donation Inquiries" (global used term is "Inquiries")
> 
> **_NEW SECTION >_ "Server Information" (Organised - Can decrease the number of threads per section)**
> - Create "Bugs" (Makes more sense to have a central location for ALL BUGS from all 3 servers - Organised - a format will be made and posted)
> - Move "Donation Inquiries" (Donation Enquiries) into here.
> - Create "Suggestions" (Central location for all suggestions - a format will be made and posted)
> 
> **"Reports & Appeals"**
> - Move the whole section down, above "Off-Topic" (Structured better)
> - Rename "Report Staff Abuse" to "Staff Abuse" (Looks better)
> - LOCK the "Staff Abuse" (Report Staff Abuse) thread so that only people that are logged in can view it.  (self-explanatory)
> 
> **"Factions"**
> - Move "General Discussion to the top, above "Faction Recruitment" (looks better)
> - REMOVE "Server Suggestions" as there will be a central location for Suggestions in the "Server Information" section.
> - REMOVE "Bugs" (Bug Reports) as there will be a central location for Bugs in the "Server Information" section.
> 
> **"Skyblock"**
> - REMOVE "Server Suggestions" as there will be a central location for Suggestions in the "Server Information" section.
> - REMOVE "Bugs" (Bug Reports) as there will be a central location for Bugs in the "Server Information" section.
> 
> **"Cannon"**
> - REMOVE "Server Suggestions" as there will be a central location for Suggestions in the "Server Information" section.
> - REMOVE "Bugs" (Bug Reports) as there will be a central location for Bugs in the "Server Information" section.
> - RENAME "Cannon Schematic Sharing" to "Cannon Showcase" (just better wording).
> 
> **"Off-Topic"**
> - REMOVE "Marketplace" - New rules (No longer allow the sale of Minecraft account to prevent issues with the owner TID'ing the account back)
> - RENAME "Staff Q&A" to "Question & Answer"
> - RENAME "Introduce Yourself" to "Introductions" 
> 
> 
> 
> 
> 
> 
> ### If these changes are made the ordering should look like:
> 
> **Server Information**
> Announcements
> Information, Guides & Rules
> Staff Applications
> Social Applications
> Guide | VenomPvP
> 
> **Server Discussion**
> Bugs
> Suggestions
> Donation Inquiries
> 
> **Factions**
> General Discussion
> Faction Recruitment
> 
> **Skyblock**
> General Discussion
> 
> **Cannon**
> General Discussion
> Cannon Showcase
> 
> **Reports & Appeals**
> Ban & Mute Reports
> Ban & Mute Appeals
> Staff Abuse
> 
> **Off-Topic**
> Off-Topic Discussion
> Introductions
> Question & Answer
> 
> 
> (For the Social Applications, Bugs and Suggestions; a format will be made for players to follow; makes it easier for us)
> 
> I guarantee you this will make the forums look less tacky.

**Comment by RoyalRaid** [comment]
All of the changes above have been made :)
Great work, Let me know if there is any others

**Comment by Zaid-Ali** [comment]
Is there any way to separate Sticky Threads from Normal threads? EXAMPLE: http://prntscr.com/dvlznc

**Comment by Zaid-Ali** [comment]
Add a new tag to go under staff members posts that just says for example:

Staff Member
Moderator 

Colour really does not matter.

**Comment by Zaid-Ali** [comment]
Remove Negative Ratings all together. There is no need for them, kids just spam them so they can get on the Most Negative Ratings list. If people disagree they can comment why, makes more sense than just disagree rating someone (counts as a negative rating) and not explaining why.

The only ratings we need are: 
- Like
- Agree
- Funny
- Winner
- Informative
- Friendly
- Useful
- Optimistic
- Creative

Of course if you remove negative ratings you will need to: 

(Maybe this gets removed with negative ratings automatically) Make sure that it only gives the positive ratings and not **_/ 0 / -0_** 
![19b32e509ad64c05bb2e3c3fe7c8eb1a](https://cloud.githubusercontent.com/assets/24858857/21993963/55f1cc94-dc15-11e6-92dd-eec7d2f7d0e1.png)



Remove the "Most Negative Ratings" on http://venompvp.org/members/?type=negative_ratings.

![195d6134ec6e455793005e9123ce629f](https://cloud.githubusercontent.com/assets/24858857/21993875/e88f50fe-dc14-11e6-99a1-0bd1ec111fc4.png)

**Comment by RoyalRaid** [comment]
I've added separate sections for sticky threads and normal threads
Ill work on tags and negative ratings soon, just gotta know what im doing xD
