### ISSUE TITLE
Staff Reform

### ISSUE THREAD

**Issue by Kauldwin** [RoyalRaid/VenomPvP#6]
reform _**Incomplete**_

_**All staff members granted extra Perms will be monitored and written down, any form of abuse with these extra powers will get you BLACKLISTED from being a + rank again, and also demoted 2 ranks, if you are Mod or below and get demoted for this, you will be removed from the staff team**_

 The + On ranks is a seperate version of the rank for staff that are more capable of certain jobs. These ranks perms can change depending on their capabilities (jobs they are good at)

_/Staff = A command that alerts all staff on the network that a Helper requires assistance and what server they're on_

Helper
**Helper is a rank for players who wish to help staff track down rule breakers and inform staff of their rule breaking, they are our eyes and ears!**
 - Warn 
    _bm.command.warn_
 - /Staff 

Trial-Mod
**A staff member can only be this rank for a maximum of 3 months. If the staff member has not proved themsleves by this time, they will be put back to Helper.**

 - /tempban (only able to tempban a max of 6 hours) 
     _bm.command.tempban_
     _bm.command.tempban.offline_
 - /TempMute (only able to tempmute a max of 6 hours)
     _bm.command.tempmute_
     _bm.command.tempmute.offline_
 - /Staff
 
Moderator (Chatmod)
**This is a moderator completely dedicated to catching and punishing rule breakers, They are also here to maintain and "teach" helpers how to do their jobs!**
 - /warn
    _bm.command.warn_
 - /jail
    _essentials.jails_
 - **List of perms to come etc**

Moderator+
**This rank is a moderator dedicated to fixing minor issues and enforcing more complicated or intensive rules, I.E Unclaiming land that surpasses the claim limit.**

Senior Mod
**Senior mods are here to oversee the lower staff, control chat with higher authority and send reports to the higher ups about the doings of the lower staff members (helpers, mods etc) They'll have extra permissions dedicated to their capabilities, factions, shops, etc**

Senior Mod+
**"Secret Admin" is a term to use for SMod+ These are those who have gained enough trust and proven their capabilites to the Admins and Owner. Theses staff have control over who to unban and reviewing staff aplications and ALL staff members doings. These staff will also be the ones to first review any staff abuse reports or anything on the forums in general. SMod+ are there to make admins lives easier**
 - Ipban/UnIPban

****

**Comment by jogavin** [comment]
Seems like a nice idea. I know a lot of players want to help but aren't active or don't know how to watch hackers. So a helper rank and chat mod rank are great for this

**Comment by Blackouma** [comment]
I'm fine with this as long as we get a safe and good /staff.

**Comment by RoyalRaid** [comment]
Definatly love the whole idea, But yeah waiting for the new /staff plugin to be coded so we can have staff safely spectate hackers and such

**Comment by Kauldwin** [comment]
*Overseer TBC
