### ISSUE TITLE
[GAPPLE TIMER] ?? There seems to be NO GAPPLE TIMER in the world

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#60]
Suddenly changed to GAP PVP, kids can chug gapples as much as the want.

./warp pvp World - Confirmed to not have a gap timer.

NOTE: **YOU NEED TO INCREASE THE TIMER TO 2 MINUTES; 30 seconds is too low.**

**Comment by RoyalRaid** [comment]
Increased gapple timer to 2 minutes *will take effect after restart*
I tested the gapple timer in the world, seems to work fine?

**Comment by Zaid-Ali** [comment]
Must've been high.  XDDD

Closing it.
