### ISSUE TITLE
[/duel] FPS ARENA Change STR2 to STR1

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#61]
In Gapple PVP Strength 2 does not work (does not allow you to drink the potion).

Either remove STR2 and replace with STR1 or make STR2 drinkable.

(Yes you did fix this a couple weeks ago but apparently it is back)

**Comment by RoyalRaid** [comment]
which arena were they in?

**Comment by Zaid-Ali** [comment]
Just the **FPS ARENA**. My bad forgot to mention in original post.

**Comment by RoyalRaid** [comment]
If i allow strength 2 in the FPS arena, it will also allow strength 2 at /warp FPS.

**Comment by Zaid-Ali** [comment]
That is a problem.

I recommend just changing the strength 2 in /duel **FPS Arena** to strength 1.

**Comment by Zaid-Ali** [comment]
^
