### ISSUE TITLE
[Anvils and Enderchests] Currently do not blow up when tnt'd

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#62]
People are starting to make unraidable walls as Anvils and Echests do not break when tnt'd. Simple fix probably in ObbyDestroyer plugin. <3

All worlds.

**Comment by RoyalRaid** [comment]
With further investigation, I looked in the materials.yml file for ObsidianDestroyer, Neither Anvils or Enderchests are enabled. And even if they were, both are enabled for TNT.

May be a issue with something else....

**Comment by Kauldwin** [comment]
I've tested this and had someone mention it, not seen it used on a massive scale 

~13

**Comment by Zaid-Ali** [comment]
Will be tested on new maps.
