### ISSUE TITLE
IGN: YouGapped/Happend [ChargeBack]

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#63]
Regarding this chargeback Happend says: 

"and wtf how can people charge back its a fucking no refund policy im fucking done you guys keep doing this to me because that fucker put yougapped at the end of a dispute you assume its me so proff dude"
"dude i dont get this splittingbases bought fly for me"
"can you check whos bank account charge backed and the name"

Just compare the ./fly purchase details to IGN: YouGapped/Happend Venomous account purchase, see if it matches to IGN: SplittingBases aka Red_Fireflys' purchases. If it was Red_Firefly IP ban the cunt.

http://prntscr.com/dvynp6 - Kid thinks he can threaten you.

**Comment by RoyalRaid** [comment]
Does anyone know his skype?

**Comment by RoyalRaid** [comment]
Will resolve with him over skype, msging him now

**Comment by Zaid-Ali** [comment]
http://venompvp.org/threads/i-was-banned-for-chargeback-yet-it-wasnt-me.1778/#post-11300

Need to resolve his ban appeal.

**Comment by Zaid-Ali** [comment]
Resolved.
