### ISSUE TITLE
[IGN: Mr_UFO] Needing Permissions Listed: 

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#64]
### [IGN: Mr_UFO] Needing Permissions Listed (Explained below): 

- mcmmo.commands.skillreset
- mcmmo.commands.mmoedit
- mcmmo.commands.mmoedit.others

- factions.bypass
- factions.admin.any
- factions.disband.any
- factions.join.any
- factions.ownershipbypass
- factions.modifypower
_(All these are in - factions.kit.mod except for - factions.modifypower)_

- auction.admin.expire

- logblock.lookup
- logblock.tp
- logblock.ignorerestrictions
- logblock.spawntools
- logblock.toolblock
- logblock.tools.tool
_(All have been included except for - logblock.rollback - logblock.me since we no longer rollback for xrayed vaults)_

- playervaults.admin

- essentials.enderchest.others
- essentials.enderchest.modify

- essentials.invsee.modify

- deluxetags.clear
- deluxetags.list.all

### Mcmmo Permission Nodes: 
We get players that use /trade and its' known issues for bypassing the cap limit to get an increased mcmmo level: http://prnt.sc/drhime http://prnt.sc/drhi3b The images shown show 3 players bypassing this limit **again**.

### Factions Permission Nodes:
To uphold the Faction Buffer Claim rule: http://prntscr.com/dvxv8n I need perms to remove any claims that surpass the limit. We currently have **Faction: Uprising** with 5 Alt factions (1000 ish power each) buffer claiming for their main base. Totaling to 120 claims which surpasses this limit. 
**- factions.modifypower** is for those who have 100 power (They had their powerboost and did /powerboost which gave them 40 more on top of the current (20 Power Originally + 40 + 40 = 100 power))

### Auction Permission Node:
We get people like this: http://prnt.sc/du05rj as well as people who try to scam others by selling "Ranks" on their (Donation Scamming). With this permission node I can forcibly remove the listing instead of waiting for yourself.

### LogBlock Permission Nodes:
Pretty self explanatory. I need the perms to block check since we get xrayed vaults reported daily. With the logs clearing every 3 days I would like to be able to ban them on the spot instead of waiting a couple of days and possibly losing the log (letting the xrayer off the hook). If you want to look over what the permission nodes do: https://github.com/LogBlock/LogBlock/wiki/Permissions

### PlayerVaults Permission Nodes: 
Once again self explanatory, In the event I need to look for illicitly obtained items (i.e. Hacker kills players - gets banned - Return the items to the player).

### Essentials EnderChest Permission Nodes:
Once again self explanatory, In the event I need to look for illicitly obtained items (i.e. Hacker kills players - gets banned - Return the items to the player).

### Essentials Inventory Permission Nodes: 
We get players that [item] spam named items such as "Ni****" "Coo*" etc. You get the picture. I generally kick and ban but I cannot remove the item and/or perm to [item] right then so this node would just help that.

### Deluxe Tags Permission Nodes:
To clear inappropriate tags that players buy for each other (i.e. "Ni****") on the spot instead of having to wait for OP's to remove it.

**Discuss it with Jack/Andre. @Kauldwin @Blackouma**

**Comment by Blackouma** [comment]
Added.
