### ISSUE TITLE
[@ANDRE @MATT] Staff Interviews/Selection

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#65]
(If you can't tell, I'm a little T R I G G E R E D)

I've messaged you so much to do this so I'm just going to make this on GitHUB and HOPE that you fucking read this.

Two staff to interview: 
- http://venompvp.org/threads/v1point0s-staff-application.1576/
- http://venompvp.org/threads/darkees-trial-mod-application.1515/

We need staff especially on **Factions** where I find I am the only one on for 6 hours straight in a day. When I log off (of course) there are no staff on Factions. I get msged by King Potato aka Nonga aka Josh that kids are spamming chat, hackers in pvp and generally players being morons when there are no staff online. I wake up at fucking 4am, deal with the cunts and then go back to sleep. This happens EVERY FUCKING DAY. Example: ![ada001ffeac82564f0abc41f1eb4da5dc4e303fa80ebcb3567 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/24858857/21965641/f6757d7e-db5b-11e6-836f-192055238c4b.jpg)

Of course hiring two new staff will not fix this but I want this wave to be selected so that we can UPLOAD the new STAFF FORMAT ready for the February AD. 

@Blackouma @Andre What are you doing......? You are on Venom for less than an hour a day, and then you disappear for the rest of it. You only reply to a message on skype if I spam you with it. You have become a SLOTH. Players notice your inactivity so do staff. It's as though you don't give a shit anymore (to put it blatantly)

I'm going to say this again...
**_SCHEDULE THE INTERVIEWS FOR THOSE 2, IDGAF WHEN YOU SET IT, JUST DO IT._**

(If you can't tell, I'm a little T R I G G E R E D {understatement})

**Comment by Kauldwin** [comment]
Completely agree

**Comment by OkHeigo** [comment]
+1, I honestly feel like it would be for the best if you would just give Zaid the permission to recruit staff for now. Andre is pretty much dead when it comes to Venom.

**Comment by Zaid-Ali** [comment]
Contacting the candidates and organising their interviews (all on Saturday). Myself and Rhad will conduct the interviews.

Closed.

********

Not resolved.
