### ISSUE TITLE
Worldedit Block Limit

### ISSUE THREAD

**Issue by Kauldwin** [RoyalRaid/VenomPvP#66]
@RoyalRaid Please lower the block limit to prevert accidental biome terraforming, Not sure WHO did it but it was larger than the current warzone.

_Image https://gyazo.com/7ef0e3403d2003fc7daee77c22fc9da1_

**Comment by RoyalRaid** [comment]
I dont even world edit things, so it couldnt of been me. Would of been you or andre.
What did you want me to set the limit too?

**Comment by Blackouma** [comment]
I've worldedited things on Venom but nothing like that. Might of accidentally done it but doubtful. I'd say set it to like 500 blocks because I doubt we'd ever need to do more. Unless Jack wants higher.

**Comment by Kauldwin** [comment]
500 blocks is less than spawn itself, 100,000 will do.

**Comment by RoyalRaid** [comment]
Set the cap to 100k
