### ISSUE TITLE
[Auto-Restarts Plugin] Needs adding!

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#67]
**The servers' performance starts to decline after a few days of constant activity resulting in a great number of lag spikes (TPS Drops) as well as the eventual crashes.** 

### Why you should add an AutoRestart plugin to restart at offpeak times? 
Off-peak =  9pm {**AU Time**} where there is only 10-15 players on factions

- You might say you don't want to lose the playerbase by adding AutoRestarts but at off-peak times the majority are likely to be AFK, therefore you effect the minority of players for the benefit of the majority of the community (less lag spikes, less crashes - better community).

- The thing that would piss me off if I was actually playing on Venom would be the constant lag spikes, especially while PvPing where you just freeze for a good 5-20 seconds which myself and multiple staff have witnessed. The lag spikes increase in frequency and generally make Venom un-playable which causes players to give up (log off - quit).

- Without AutoRestarts the server only gets restarted in the event of a server crash which is an obvious disadvantage as _config changes only take place when the server is restarted_. Takes around 5 days for changes in the config to take effect whereas _they COULD have been implemented the following day (following restart)_ if AutoRestarts were to added.

************************

### At this point you might be thinking that you don't feel the server needs to restart everyday, only when needed.

./restart: Simple plugin allows whoever is given the perms to restart the server. Staff such as one **or** both the admins would have access to restart when the Venom becomes un-playable (when there starts to be frequent lag spikes).

This would obviously be used less than if you were to AutoRestart everyday which would basically means that there are less restarts (less kicking players offline) for 1-5 minutes while the server reboots. 

ALL TODAY:
![screenshot_1](https://cloud.githubusercontent.com/assets/24858857/21990379/7ce3c122-dc06-11e6-838c-e6c221bd969a.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/24858857/21990399/96314ec4-dc06-11e6-98be-6054c8c60ed1.png)
![newewewewe](https://cloud.githubusercontent.com/assets/24858857/21998065/a34a2788-dc2a-11e6-8842-26a347da41b3.png)
![ss](https://cloud.githubusercontent.com/assets/24858857/22000258/12ef4090-dc36-11e6-8820-aa2cce37e1c2.png)

************************

The obvious better option would be the AutoRestarts everyday at Off-Peak times so that the server can run at maximum efficiency - least amount of lag - happier players - changes to configs implemented the following day. 

If you are still on the edge about adding AutoRestarts, well **:?**.

There are only advantages of adding AutoRestarts in both the short term and long term. I don't see kicking _a very small amount of players_ for 1-5 minutes everyday while the server restarts to optimize their experience on Venom a disadvantage.

**Comment by RoyalRaid** [comment]
Very detailed issue, Love it :)
I've setup auto restarts through multicraft (our server control panel), just like skyblock has. Hopefully this will help the server out a lot. The reset will run every 24 hours starting at 9pm (AU TIME).

Great work UFO <3
