### ISSUE TITLE
[@Matt] Need files to complete "Staff Reform" changes

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#68]
Please **DO NOT** pastebin the configs just right click and **COMPRESS** the folders for: 

Group Manager Folder + Plugin (JAR FILE - OLD Version of GM?)
DeluxeChat Folder + Plugin (JAR FILE - **NEEDED!!!** Its an OLD VERSION of DELUXECHAT)

When I say folder, I literally mean the whole folder that shows when you look in the plugins folder. Just COPY and PASTE the Group Manager and DeluxeChat .JAR Files into the folders **AND THEN COMPRESS**.

I need the JAR files as the DeluxeChat plugin has been updated meaning the configuration layout has changed and automatically adds the updates to the config. When we send the configs back to you there will be unneeded lines and basically it is just unnecessary.
*************
Why do I need the whole folders? - We need to test everything before we send you the config and change it on Venom so that there are no problems (having to ask you to change shit).

Thank you in advance.

**Comment by Zaid-Ali** [comment]
#6

**Comment by RoyalRaid** [comment]
Who are these files going to? Ill zip and send over skype?

**Comment by RoyalRaid** [comment]
Files sent to Zaid. Marking as resolved
