### ISSUE TITLE
Pot glitch

### ISSUE THREAD

**Issue by Kauldwin** [RoyalRaid/VenomPvP#69]
https://gyazo.com/4a3efabbf9b5b9f36cd904bac72ac051  

Update ; -

Only one report of this from Kodi(Light) not sure how or where she got them but it could possibly be abusable, I've seen servers where it doubles the affect of the potion. I will keep updated once more info is gathered. ~13

**Comment by RoyalRaid** [comment]
More info pls :)

**Comment by Zaid-Ali** [comment]
Closing until more information is posted.
