### ISSUE TITLE
Removal of a fac

### ISSUE THREAD

**Issue by Paige-leee** [RoyalRaid/VenomPvP#70]
https://gyazo.com/ed94945424de48f3b06bbe23afee6d3e
https://gyazo.com/c40a8c3e8b913d55ce181dd53439f9dc
https://gyazo.com/966fb9734a2a73c9739b00e80f6b7969
https://gyazo.com/4d58c6c7856bf93fd13f153ef69d076f

**Comment by RoyalRaid** [comment]
They have been disbanded, Thanks :)

**Comment by Zaid-Ali** [comment]
Ign: Miniter, recreated the faction. Temp banned.
