### ISSUE TITLE
[Crate Plugin] Crashed / Does no longer work

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#75]
Vote keys are not given upon voting. 

All the crates no longer work.

Most likely an error in config / plugin just shat itself.

**Comment by Kauldwin** [comment]
***Critical needs fixing ASAP**

**Comment by RoyalRaid** [comment]
Fixed on both server,
Not fucking sure why but the cratekeys jar file removes itself, if it happens again then ill investigate but for now its fixed
