### ISSUE TITLE
[/wild] Need to check that it is disabled in 

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#76]
When you do /wild it brings up the following message:

"Venom// Executing /wild in 5 seconds ..."
* After 5 Seconds it says
"Usage: /fbasics <reload;version;safepromote;wilderness>"

Example:
![screenshot_3](https://cloud.githubusercontent.com/assets/24858857/22032485/84429340-dcdc-11e6-87bf-7a4f09a94c02.png)

**********
Make sure FBasics wilderness is disabled in the config and then do **/fbasics reload** then and there. 

Then test out the new /wild.

**Comment by RoyalRaid** [comment]
All fixed, the issue was the warmup for /wild was still ran through Fbasics, Everything is working now
