### ISSUE TITLE
[Staff Interviews] Status

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#77]
### This is an ongoing process

******************************
**All the successful applicants Rhad and I are going to / already have interviewed _that should be promoted_ >>>> Skype Usernames have been provided**

IGN: Darkee (Skype: **Darkness7677**)- Application is good. _Interview was solid_, generally confident, has previous staffing experience and knowledgeable. Maturity - I'd say he is much more mature than most of the current staff (which is not a bad thing). Will staff on Factions. _**Highly Recommended by myself**_

IGN: V1Point0 (Skype: **battlefiend1021**)- Application is good. _Good Interview_, seems to be very mature for Skyblock. Will staff on Skyblock. **Highly Recommended by myself**

IGN: KavinSky (Skype: **.**)- _Yet to be interviewed

**Hire them separately or all at once - Up to you** @Kauldwin @Blackouma @RoyalRaid 

************************

### When hiring these 2 new staff make sure you set their forum ranks and post these in the appropriate sections: 
(More organised - Staff Application has been made more specific and generally just better)

http://venompvp.org/threads/template-staff-application-format.1495/
http://venompvp.org/threads/template-staff-abuse-format.1771/ <-- Add a section to "Accepted / Denied"
http://venompvp.org/threads/template-bug-report-format.1770/ <-- Add a section to "Resolved"
http://venompvp.org/threads/template-donation-inquiries-format.1772/ <-- Add a section to "Resolved"
http://venompvp.org/threads/template-ban-mute-appeal-format.1774/

*****************************

### The following people were rejected:
IGN: RelaxYourBad - **REJECTED** - Immature
IGN: BrewCrew28 - **REJECTED** - Not ready for the role

**************************
### @MATT
**Check Skype @RoyalRaid for the current staff promotions**

**Comment by RoyalRaid** [comment]
If everyone else is happy then ill release my update log with these new staff

**Comment by Blackouma** [comment]
I am happy with the two applicants. Do we have both on Skype? If not ask them to start a convo with me sending their Skype names. Is there anyone else who should/will be interviewed? I recommended RelaxYourBad (he's been good with me and recommended the BLSquad program). There's also BrewCrew, Antplourde and Kavinsky left. I +1 Kavinsky and RelaxYourBad, don't know about the other two.

**Comment by Zaid-Ali** [comment]
Update 1.

**Comment by Zaid-Ali** [comment]
Closing thread - Staff will be hired upon reset.
