### ISSUE TITLE
[/list] Possible problem

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#78]
The Premium version of the /list plugin: 
I was assured by the plugin dev that it was hooked into essentials meaning when a player does /vanish they do not appear on /list. 

However this version (free version) doesn't have that feature. So when I am in vanish they can see me in /list. ;c

Aids, I know.

You could just keep the free /list for now and update to the premium version once the dev has finished re-optimizing the plugin.

It's up to you.

**Comment by Kauldwin** [comment]
The /List plugin also bugs out and displays me when I'm not online, Tested as of Right now

**Comment by RoyalRaid** [comment]
I would purchase the premium version of it, but there is a issue with the authors paypal account: https://puu.sh/tq73L/4bbdf94c81.png

As for jack's comment /list will be removed from VenomCore plugin and /list & /staff will be used by the new GUI plugin

**Comment by Zaid-Ali** [comment]
Will notify if there are any problems with [/staff].
