### ISSUE TITLE
Site Confirmation E-mails [Not being received]

### ISSUE THREAD

**Issue by Kauldwin** [RoyalRaid/VenomPvP#8]
People aren't getting their verified emails within the day of registering it can take upto 3 days to come through. Had 3 players complain about this, This is stopping users signing up to the forums

**Comment by RoyalRaid** [comment]
Have they checked their spam/junk folder?

**Comment by RoyalRaid** [comment]
Closing this issue! as most of the cases that people couldnt confirm their account was because they already had a account with the same email or it was in the junk folder!

**Comment by Zaid-Ali** [comment]
Issue still exists: http://prnt.sc/drg0ku

Checked both his mail and he confirmed he did not have an account with the same email.

**Comment by Zaid-Ali** [comment]
http://venompvp.org/members/jason.983/ Same issue.

**Comment by Zaid-Ali** [comment]
http://www.venompvp.org/members/steveisallama.996/ Same issue.

**Comment by Zaid-Ali** [comment]
http://venompvp.org/members/insusceptibility.1022/ Same issue.

**Comment by RoyalRaid** [comment]
hm, Im gonna investigate further with this, Might have to setup some new email settings.

**Comment by Blackouma** [comment]
When two of my friends were screwing around and trying to make troll apps it took them a while to get the emails, they checked the spam folders and I was sitting right next to them as they signed up and such so I know they didn't enter anything wrong. I'm not sure if they ever even ended up getting the emails.

**Comment by RoyalRaid** [comment]
did they use the same email to register?

**Comment by Zaid-Ali** [comment]
http://venompvp.org/members/molten23.1056/ Same issue.

**Comment by Zaid-Ali** [comment]
Resolved.
