### ISSUE TITLE
Removal of Factions part 2

### ISSUE THREAD

**Issue by Paige-leee** [RoyalRaid/VenomPvP#80]
https://gyazo.com/a08417212e9b7279ad7fe681326df5e3
https://gyazo.com/66fe82a7f2a2d7f5f7cb0f5dc17fa8e8  (maybe??)
https://gyazo.com/82e24bac3fc2643d3a56203fc73c95fa (maybe??)

**Comment by RoyalRaid** [comment]
Removed the "NIGGERCOON" faction, the other two im partly okay with

**Comment by Paige-leee** [comment]
okay
