### ISSUE TITLE
Changes for next reset:

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#85]
### Death Message ###

Currently: 
![caade0926e414052bf0b00d95529d0b6](https://cloud.githubusercontent.com/assets/24858857/22399234/627b1de2-e590-11e6-94d8-dc2464257aeb.png)

Change it so that it says &c{PLAYER-NAME} &7was slain by &c{PLAYER-NAME}
Remove the "by Diamond Sword" as there is no point really.
Example: 
![c14d1c6ecae041e085a3b28fb85d2931 1](https://cloud.githubusercontent.com/assets/24858857/22399232/5b19a910-e590-11e6-821a-c5763aafd628.png)

### Crates

**Vote Crate**

Remove "30 XP Levels" and....
Add these items:
1. 32 Iron Blocks
2. 16 Gold Blocks
3. 16 Diamond Blocks
4. 32 x EXP Bottles
5. 64 x EXP Bottles

**Vote Party Crate**
**NEEDS REMOVING COMPLETELY OR NERFING MAJORLY** 

Reasoning: 
Currently have players using VPN's logging on alts and just farming VP Keys (by just keeping them online for days on end), they trade the keys to the main accounts and get mass amounts of VP Keys. One of the factors that just ruined SB's economy.

Fixes:
- Remove VP Keys completely and possibly just add DP's (Drop Parties) instead as it will prevent alts obtaining gear and items. 
- Majorly nerf VP Crates, then again who wants to open shit crates...

### Clear Lagg Plugin Message

Make the warning messages stand out more so that people know when its happening:
Example: 
![466308c05b5e49c397280322a8c88006](https://cloud.githubusercontent.com/assets/24858857/22399225/3eca09da-e590-11e6-988a-048702216da9.png)

Colour Code:
```
'&8(&2&l!&8) &2&lWARNING: &7Removed &2+RemoveAmount &7entities!' 
&2&lWARNING: &7Entities will be removed in &2+remaining &7seconds'
```

### Buycraft Rank Perk (Suggestion Only)

Permission Node: **auction.limit.#** 

You can make it so that as you go from explorer to python (for example) you can list more items on /ah at one time. Same for all the ranks, just +1 onto the perm.

Just an extra perk, more incentives I guess xD.

### Add /border

We get asked by new players "What is the border?".

Might as well add **./border** which tells them:

Example:
![4222cde5ce1642c1b2dc8f8af27262c9](https://cloud.githubusercontent.com/assets/24858857/22399428/3cafeca6-e594-11e6-8a03-ce7485e146f7.png)
You can experiment with the colours and stuff, I just whipped that one up.

### Add the alias ./ts

Currently have **./teamspeak**. Might as well add **/ts**, the abbreviation of TeamSpeak.
![screenshot_4](https://cloud.githubusercontent.com/assets/24858857/22399702/84bd9eac-e59a-11e6-8407-1266c7e7039d.png)

Message:
![58986b58786c44dc862a763eac59ddb5](https://cloud.githubusercontent.com/assets/24858857/22399463/eb478a1c-e594-11e6-8b2a-00ba27e50219.png)
You can also get rid of those extra empty lines shown in the image. Only need 1 each side.
^^ Same with **./discord**. Message:
![13d8d2cc1ac84dbdbdbbb8100f0a1495](https://cloud.githubusercontent.com/assets/24858857/22399577/292c9e38-e597-11e6-816c-c5cb4653c572.png)

### Add a ./report plugin

Pretty much needed for a factions server. No harm really can be done by adding this. More reports made more players watched, possibly more hackers banned.

Currently recommend this one: https://www.spigotmc.org/resources/advancedreport-over-11k-downloads-1-7-1-8-1-9.5759/

Tested it out on the T Server and it works as expected. 

You could also get **./report** hooked into the Staff Plugin the dev may be developing.

### KOTH Schedules

Current Koth Schedule: 
![bc3e669c12514ac2afdcc50bf0ccfaf5](https://cloud.githubusercontent.com/assets/24858857/22399652/66d91660-e599-11e6-9f51-241b76aea60e.png)

Increased playerbase means more people from different parts of the world logging on to Venom. The current koth schedule is preferential to weekends and those in the AU and US. For those in the UK and EU area KOTHs happen quite late at night where I'm assuming most kids would go off Venom.

**Preferred Koth Schedule** would be "**Daily Koths**"; more people that can participate the better.

Example Schedule:
![screenshot_1](https://cloud.githubusercontent.com/assets/24858857/22399671/cd242aae-e599-11e6-8bec-10b400db28a9.png)

The example shows a KOTH every 5 hours. Sidenote: The way I have laid out the koth schedule appeals to my OCD. Please use it as a guide when you change **/koth schedule** xD.

### Add the alias ./k

You currently have to type **./koth schedule** to get the times for KOTH. Just add ./k which shows the Koth Schedule.
![screenshot_2](https://cloud.githubusercontent.com/assets/24858857/22399693/5e162800-e59a-11e6-8a45-dceea5680cea.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/24858857/22399699/6c82e004-e59a-11e6-8383-66aee5d0344a.png)

### Combat Log Timer

Increase the combat log timer to **20 seconds** instead of 15.

### Faction Top Changes

Currently when you do **./f top**:
![screenshot_6](https://cloud.githubusercontent.com/assets/24858857/22399818/811a0404-e59d-11e6-806b-ae19ede52443.png)

At the top the amount of these things ![screenshot_8](https://cloud.githubusercontent.com/assets/24858857/22399910/5ad08fdc-e59f-11e6-9ce5-8f559b9949dc.png) need to be reduced to around 3 - 5 on each side. There is just an unnecessary amount of them and it makes my OCD cut. 

You need to change "**Faction Top**" to "**Top Factions**".

Fix the extra line before the letter "**F**".
![screenshot_9](https://cloud.githubusercontent.com/assets/24858857/22399921/b5eb2918-e59f-11e6-9098-de0aea373e63.png)

Currently when you **hover** over a faction:
![screenshot_7](https://cloud.githubusercontent.com/assets/24858857/22399821/95ad23e2-e59d-11e6-8556-e59eb2b85e39.png)

As you can see it looks pretty bland and default. The **updated version** of Factions Top (LINK: https://www.spigotmc.org/resources/new-update-factions-top-f-top-for-factionsuuid-massivecore-factions.16249/) allows you to customize litterally everything to make it look better.

Recommend adding these sections:

-- General --
Total Worth: $#
Block Worth: $#
Spawner Worth: $#

-- Spawners --
Enderman: #
Cow: #
Sheep: #
Chicken: #
Spider: #
Skeleton: #
Blaze: #
Zombie Pigman: #
Creeper: #
 
-- Blocks --
Hoppers: #
Emerald Block: #
Diamond Block: #
Gold Block: #
Iron Block: #

Example:
![screenshot_5](https://cloud.githubusercontent.com/assets/24858857/22399893/e93c82b8-e59e-11e6-81e9-1a3bbdc42033.png)

The placeholders are as follows:
- %totalwealth%
- %spawnervalue%
- %blockvalue%

- %spawners%

- %blocks%

### ./f help Configurable

Current **./f help**:
![screenshot_10](https://cloud.githubusercontent.com/assets/24858857/22399956/61718fac-e5a0-11e6-9d92-0261446ef83b.png)

The current **./f help** is default and ugly. Factions UUID allows you to configure all of ./f help. Change the layout and remove the unnecessary pages of it.

If you would like me to do it send me the folder with the config.

![screenshot_11](https://cloud.githubusercontent.com/assets/24858857/22399968/b3cd2392-e5a0-11e6-9d2e-9a363f57e789.png)

### ./f list and ./f who  Configurable

**Current ./f list:**
![screenshot_12](https://cloud.githubusercontent.com/assets/24858857/22399978/e3bd80ba-e5a0-11e6-9808-874c355d7f28.png)

As you can see its default once again, can be made more appealing by changing the colours and layout.

**Current ./f who:**
![screenshot_13](https://cloud.githubusercontent.com/assets/24858857/22399986/45cb005c-e5a1-11e6-9416-a5e5ffe597a8.png)

Recommend: 
![screenshot_15](https://cloud.githubusercontent.com/assets/24858857/22400178/dbacbb66-e5a5-11e6-851a-fdc14aba6514.png)

(Something I whipped up in a couple of minutes) Making it look better. There is no need for "Founded, Land Value and Balance".

Code:
```
show:
  # First line can be {header} for default header, or any string (we recommend &m for smooth lines ;p)
  - '&8&m-&2&m-&8&m-&2&m-&8&m-&2&m-&8&m-&8[ {faction} &8]&8&m-&2&m-&8&m-&2&m-&8&m-&2&m-&8&m-'
  - '&aJoining: &e<i>&e{joining}    {peaceful}'
  - ' '
  - '&aLeader: <i>&e{leader}'
  - '&aDescription: &7<i>&e{description}'
  - '&aLand / Power / Maxpower: &8<i> &e{chunks}/{power}/{maxPower}'
  - '&7This faction is permanent, remaining even with no members.' # only shows if faction is permanent
  - '&aAllies: {allies-list} '
  - '&aOnline: (<i>{online}&a): &f{online-list}'
  - '&8&m-&2&m-&8&m-&2&m-&8&m-&2&m-&8&m-&2&m-&8&m-&2&m-&8&m-&2&m-&8&m-&2&m-&8&m-&2&m-&8&m-&2&m-&8&m-&2&m-&8&m-&2&m-&8&m-&2&m-&8&m-&2&m-'
```

### Coinflip Layout

Current **./cf**:
![screenshot_16](https://cloud.githubusercontent.com/assets/24858857/22400212/c15f156e-e5a6-11e6-80b7-3c3f49768862.png)

Change the "Games Available" colour code to "**&b**".
You can also change the colour of the 6 glass panes.

Recommended: 
![screenshot_17](https://cloud.githubusercontent.com/assets/24858857/22400225/fa6da190-e5a6-11e6-8bde-53b7294cf5b9.png)

Just looks better.

### ./who ./list Changes

Current **./who**:
![screenshot_18](https://cloud.githubusercontent.com/assets/24858857/22400243/2ec77cfe-e5a7-11e6-8aff-31d2f2a65e79.png)

Add the all the donator + default ranks into the config so that when they are online it shows their group and names beside it. 

![14759e00f1a44286aec1e0e58dc18f21](https://cloud.githubusercontent.com/assets/24858857/22400274/4517300c-e5a8-11e6-9840-cea213f178e8.png)

### Custom Named Items (Suggestion Only)

People love to name their swords and armor but they want to be able to use colour and bold etc. So the suggestion is to get a plugin developed that allows the user to for example:

Have an item in their hand.
Type /nameitem &4&lMr_UFO's Whip
It them gives them a preview of what it will say and makes them type or click some sort of verification.
It takes **$50,000** from their balance.
It takes the item in their hand and renames it to that nick.

There would be safeguards such as too many colours (blocked italics and magic and strikes) and not being able to name an item if it **IS NOT** full durability.

### KOTH Messages
They are honestly disgusting rn. XD

You want to change it to something more appealing to people.

Example:
![screenshot_19](https://cloud.githubusercontent.com/assets/24858857/22400552/04f8f5c0-e5b0-11e6-8acb-e5decf71cdba.png)
Use those as guides for the rest.

You can also make it so that when a koth is on the scoreboard pops up which shows:
![screenshot_20](https://cloud.githubusercontent.com/assets/24858857/22400588/2285c720-e5b1-11e6-99ef-af9e963e02ad.png)

**Comment by RoyalRaid** [comment]
Replied to you on skype :)

**Comment by Zaid-Ali** [comment]
### Crate Keys Lore

Change the lore of each crate key to:
![screenshot_22](https://cloud.githubusercontent.com/assets/24858857/22405176/55729124-e636-11e6-9948-327443d6798c.png)
![screenshot_23](https://cloud.githubusercontent.com/assets/24858857/22405177/570fb08e-e636-11e6-8d19-e52704a0a802.png)
![screenshot_24](https://cloud.githubusercontent.com/assets/24858857/22405178/586b69d2-e636-11e6-9f53-dc8533e1b826.png)

Just looks better.

### Vote Messages

Currently just spams with:
![screenshot_25](https://cloud.githubusercontent.com/assets/24858857/22405221/39708818-e637-11e6-8a9d-338a802d28a7.png)

Change it to something like: 
![screenshot_27](https://cloud.githubusercontent.com/assets/24858857/22405306/ab8351e6-e638-11e6-9605-9dcb068e5dd7.png)
or....
![screenshot_28](https://cloud.githubusercontent.com/assets/24858857/22405334/fc61969a-e638-11e6-9b42-99bab0362dab.png)


### 2x Rewards ./vote (Suggestion Only)

On the first week of the reset make it double the amount of vote keys/rewards. Just a HUGE incentive to vote on that first week.

The message would be:
![screenshot_26](https://cloud.githubusercontent.com/assets/24858857/22405319/d6aa5af4-e638-11e6-9863-acc14258c693.png)
or....
![screenshot_29](https://cloud.githubusercontent.com/assets/24858857/22405340/1c0ecc6a-e639-11e6-9dd2-a01a5693a111.png)

Experiment with colour.

### Factions Leaving and Entering Messages

Currently: 
![screenshot_33](https://cloud.githubusercontent.com/assets/24858857/22405625/8d966218-e63d-11e6-918f-df15cd64a73f.png)

Recommended:
![screenshot_32](https://cloud.githubusercontent.com/assets/24858857/22405632/95311f90-e63d-11e6-84a9-2212bc3ba3aa.png)

Just aesthetic improvements.

### Vote Board (Suggestion Only)

We currently **do not have a vote board** but this is something I would imagine it would look like:
![screenshot_34](https://cloud.githubusercontent.com/assets/24858857/22405900/3fe8465e-e641-11e6-9cd5-7f2e602ffb32.png)
**CLICK ON THE PIC AND ZOOM IN**
(Something I whipped up) Just looks nice xD, you can experiment with the design etc with the spawn and sign colours. Pretty sure there are mass amounts of plugins out there that will do this.

### Skyblock: ./is coop

https://www.spigotmc.org/resources/a-skyblock.1220/ 
Plugin updated to have ./is coop (HIGHLY requested feature), update the plugin and give players the perm:

- askyblock.coop

### Skyblock: Mcmmo Caps

SB is just a clusterfuck rn. We **need** MCMMO Caps. Combat skills such as unarmed are too overpowered to not have a cap, people can one hit others with fists. 

**I suggest:**
-- General -- 
Woodcutting: 1500
Excavation: 1500
Repair: 1500
Fishing: 1500
Alchemy: 1500
Herbalism: 1500
Mining: 1500
Acrobatics: 1500
Salvage: 1000
Smelting: 1000

-- Combat -- 
Swords: 1000
Axes: 500
Archery: 1000
Taming: 1000
Unarmed: 500

### Skyblock and Factions: Blacklist words (Suggestion Only)

**Could you get the dev to hook up a command to blacklist words in-game?** 

Reason being we get people that advertise on Venom (i.e. "Spawner.Pw aka DreamRaids (bunch of cunts)), they use VPNs and just use public alts so IP banning has no effect. If we could just blacklist the word spawner(dot)pw etc. it would prevent them from being able to do so as well as the ability for admins to  add other words to it as we go.

### Skyblock and Factions: ./who and ./list

**REMINDER**
Remember to add the *UPDATED PREMIUM VERSION* of pStaffList to the **skyblock and the factions server**.
Link: https://www.spigotmc.org/resources/pstafflist-a-staff-list-in-a-gui.24838/

[The dev managed to fix his paypal; The premium version is needed as is hooked into essentials meaning if I am in vanish it will not show up on /list.]
ALSO
**REMINDER** to hook the plugin into bungee so that it shows all staff on all servers in the GUI.

### Factions: Grace Period (Suggestion Only)

https://github.com/RoyalRaid/VenomPvP/issues/25 **CLICK THE LINK**

I genuinely think you should implement this, if we get new players we don't want them to be killed instantly without the chance to build a base etc. (getting killed by donators) as soon as they drop.

### Announcement Messages

Send me the announcement plugin and configs for **BOTH SB and Factions** so that I can add some more that would be relevant.
"Why not just tell you (aka Matt) what to add?"  -  I just work better if i can actually see it and be able to change the colours etc (OCD XD).

To add (no ugly) messages about:
- Social Media [Twitter, SnapChat]
- PlugDj
- /Border
- /k
- /forums
- /discord
- Sale (i'm assuming there will be a sale at the start of reset) - pm me info
- Staff

To delete the irrelevant messages about: 
- Warp Food
- "Looking for Staff"

**Comment by Zaid-Ali** [comment]
### Duel Arenas

**Remove Arenas:**

- Arena 1 (Small, Laggy)
![2017-01-30_21 24 16](https://cloud.githubusercontent.com/assets/24858857/22443447/cfe4c3ae-e736-11e6-94f9-44bb047f0455.png)

- Arena 3 (Small, Ugly)
![2017-01-30_21 40 15](https://cloud.githubusercontent.com/assets/24858857/22443492/eeed7ec6-e736-11e6-9f8d-498ebba392eb.png)

- Arena 4 (LAGGY AF)
![2017-01-30_21 41 20](https://cloud.githubusercontent.com/assets/24858857/22443501/f6d40cae-e736-11e6-8f5a-997a2fc04cb5.png)


Rename FPS to Map 1
Rename Arena 2 to Map 1

### New Duel Map <3

![screenshot_37](https://cloud.githubusercontent.com/assets/24858857/22443532/129741a4-e737-11e6-93cb-5245ab52363b.png)

![screenshot_36](https://cloud.githubusercontent.com/assets/24858857/22443545/1d4146cc-e737-11e6-9f1a-713c9b023e2a.png)

Built by ImLovin (Rob <3) and myself.

**Comment by Zaid-Ali** [comment]
### Add the alias ./social

Add /social (**similar layout to /ts and /discord**) showing the twitter follow link and snapchat. 

Twitter: https://twitter.com/venompvp_
SnapChat: venom.pvp

### Add the alias ./apply

**Similar layout to /ts and /discord**

Link them to the staff applications section on the forums:

Apply: https://venompvp.org/forums/staff-applications.4/

**Comment by Zaid-Ali** [comment]
`UltimateAnnounce:
  Chat:
    Prefix: &8(&a&l!&8)
    Header: &r
    Footer: &r
    space-between-messages: false
    Sound: NOTE_PLING
    Messages:
    - &7Want to stay updated with the &c&llatest news&2?%n&7Come and join us now at &a&l/forums&2!
    - &7Do you enjoy listening to &c&lmusic&2?%n&7Be sure to join the &a/plugdj &7now&2!
    - &7Be sure to follow us on &6&lsocial media&2! &c&l/social
    - &7Did you know you get rewards for &6&lvoting&2?%nVote now using &a&l/vote&2!
    - &7Do you want to &6&lwin a rank&2?%n&7Become a top voter now&2!
    - &7Bring &c&ldeath to your &c&lenemies&2! &a/warp pvp
    - &7Be sure to use &a&l/wild &7to escape spawn easily&2!
    - &7Make sure you &5&lvote &7to claim your rewards&2! &a&l/vote
    - &7Hover over a players’ name to see their stats&2!
    - &7Be sure to keep updated with our rules&2! &a&l/rules
    - &7Did you know we have a &6&lcoinflip&2?%n&7Check it out with &5&l/cf&2!
    - &7Do you feel you have what it takes to become a &a&lmember of staff&2?%n&7Feel free to apply now by using &6&l/apply&2!
    - &7Did you know we have &5&lcombat statistics plugin&2?%n&7Check them out using &a&l/killstats&2!
    - &7Find out world borders using &c&l/border&2!
    - &7Did you know we have a discord server setup for VoIP?%n&7Check it out using /discord&2!
    - &7Did you know you could purchase &c&lcustom tags&2?%n&7Check it out using &a&l/buy&2!
    - &7Did you know you can place &5&lbounties on players&2?%n&7Try it out using &a&l/bounty&2!
    - &7Purchase our unique &a&lVenom Perks using &c&l/token shop&2!
    - &7Feel free to ask a &a&lmember for staff &7for help when they are online&2!
    - &7Did you know you check check your own and other players &a&lping&2?%n&7Try it out using &5&l/p&2!
    - &7Make money on the go using &a&l/sell&2!
    - &7Make sure you &5&lvote &7to claim your rewards&2! &a&l/vote
    - &7Koths run &c&ldaily&2!%n&7Check out the schedule using &a&l/k&2!
    - &7Did you know there are regular envoys in the &c&lWarzone&2?%n&7Check out the next envoy using &a&l/sc time&2!
    - &7Try out our new &d&lduel system&2! &a&l/duel
    - &7Need the TeamSpeak IP? &a&l/ts
    - &7Purchase items on the store &afor your advantage&2! &a&l/buy
    Interval: 300
    Enabled: true
    Random: false
  Action:
    Messages:
    Interval: 0
    Duration: 600
    Enabled: true
    Random: false
  Title:
    Messages:
    - &7Demo Title message
    - &7Plugin created by Th3Tr0LLeR
    - &7Hello &a<player>&7! There are &a<online> &7players.
    - &7Your health: <health>
    - &7Your level: <level>
    Title: &7-=[&7Default Title&7]=-
    Interval: 50
    Enabled: false
    Random: false`

**Comment by RoyalRaid** [comment]
@Zaid-Ali Please close this thread and make a new one with anything i've missed :)
