### ISSUE TITLE
Hub Bugs and Issues

### ISSUE THREAD

**Issue by Blackouma** [RoyalRaid/VenomPvP#86]
## 1. AFK Players in Hub ##

There's been around 20 players in hub at all times for a while now. An afk timer (10-15 minutes) needs to be added to the hub so these players can't be on forever. It makes us look bad because players will in most cases assume that they're all bots that we have to make it look like we actually have players.

![c1a8736375478fed3d4a2ae522a7af1d](https://i.gyazo.com/c1a8736375478fed3d4a2ae522a7af1d.png)

## 2. Inaccurate amount of players in Multiplayer tab. ##

Even with the AFK players in the hub the Multiplayer tab shows Venom having a number of players that it does not actually have. Just with the AFK players in the hub, from the players POV it may look like those players are all bots.

![a2ce181ce1eb78254d3fdc1b4105d97f.png](https://i.gyazo.com/a2ce181ce1eb78254d3fdc1b4105d97f.png)

## 3. Individual server players bug. ##

Instead of saying the player amounts in the sidebar it shows {bungeecount}, and it's been doing that for a week or two now.

![2637507518a9a4e8e5f9f9cab48cb545](https://i.gyazo.com/2637507518a9a4e8e5f9f9cab48cb545.png)

**Comment by Zaid-Ali** [comment]
### AFK Players in HUB
This is most likely due to the autorestart that happens on SB - the players were most likely already afking a farm etc. 

The idea to add an auto AFK kick in hub is **alright**.

### Individual server players bug
"Server restarts kicking players to hub"
