### ISSUE TITLE
Issues / Fixes Need to be made for Reset Map:

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#88]
### TNT Mechanics

Currently set to 1.8 tnt mechanics so tnt flows with water (**AIDS**). Change to 1.7 mechanics. 

### Lava Flow Speed

Quite slow right now. Increase the speed of lava flow (**CONSIDERABLY**).

### Change ./vote

No need for these:  
![screenshot_3](https://cloud.githubusercontent.com/assets/24858857/22608408/9c256084-ea54-11e6-93a9-8e8e89f922e5.png)

Just make it these: 
![screenshot_4](https://cloud.githubusercontent.com/assets/24858857/22608421/b077de40-ea54-11e6-93e0-77861ee027b7.png)

Also try to centre everything because my OCD wants to CUT.
Example:
![screenshot_2](https://cloud.githubusercontent.com/assets/24858857/22608435/bf9759c8-ea54-11e6-9e65-c7c1f4a3a672.png)

### Death Messages

There are no death messages right now. Activate them.

### Blocks not taking damage from TnT

![screenshot_5](https://cloud.githubusercontent.com/assets/24858857/22612714/5eed89a6-ea6a-11e6-93de-f656950a610a.png)

Currently, ANVILS, ENDERCHESTS and ENCHANTMENT TABLES do not get blown up by TNT. 

Check ObbyDestroyer.

### Combat Remove Command

You can do **./shop** in combat - **REMOVE**

### Formatting Issue with new @ plugin

![screenshot_6](https://cloud.githubusercontent.com/assets/24858857/22612918/d1f5ba1c-ea6b-11e6-9bc3-aad572110055.png)

Changes players chat colour after they mention a staff member.

As seen when Rob @Mr_UF0's me

### Buycraft Kit Timers

The time between kits needs to be increased from the current **24hrs** to **36hrs** - less pay to win.

### VenomUtils

Currently take fall damage and have hunger.

### Faction Commands

Check that you have added the configuration for f top and test the commands:

- /f who
- /f list
- /f top

**Comment by RoyalRaid** [comment]
![javaw_2017-02-10_12-41-55](https://cloud.githubusercontent.com/assets/19232463/22810694/704bb87a-ef8e-11e6-996b-a5a52e43c5c9.png)
Seems to be centered for me, but i've changed the header and footer

As for lava flow and tnt mechanics, they aren't set till we move everything over from beta to the main server

**Comment by Zaid-Ali** [comment]
### Add the alias ./social

Add /social (similar layout to /ts and /discord) showing the twitter follow link and snapchat.

Twitter: https://twitter.com/venompvp_
SnapChat: venom.pvp

### Add the alias ./apply

Similar layout to /ts and /discord

Link them to the staff applications section on the forums:

Apply: https://venompvp.org/forums/staff-applications.4/

### Add the alias ./sc time

./sc time should mimic the command ./supplycrates schedule.

@RoyalRaid

**Comment by RoyalRaid** [comment]
Added /social, /Sc and /Apply. Please close thread and add any other suggestions to a new thread pls :)
