### ISSUE TITLE
Manually Send Email Confirmation on Forums

### ISSUE THREAD

**Issue by Zaid-Ali** [RoyalRaid/VenomPvP#9]
Link: http://venompvp.org/members/kalle.758/

Has not received his email confirmation, requires it to post his application. Manually send it.

**Comment by Kauldwin** [comment]
https://github.com/RoyalRaid/VenomPvP/issues/8 Similar issues

**Comment by RoyalRaid** [comment]
The issue was with Kalle, they already had a account with that email, I went ahead and confirmed it manually though
